name: send

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTION }}
        with:
          source-directory: 'output'
          destination-github-username: springhana
          destination-repository-name: creavispace
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: vercel
      - name: Test get variable exported by push-to-another-repository
        run: |
          rm -rf .github/workflows/deploy.yaml
          echo $DESTINATION_CLONED_DIRECTORY
